on:
  schedule:
    # Runs every hour
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest MAL history
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MyAnimeList readme workflow
        uses: MoonLGH/MAL-autoreadme@v2
        with:
          username: "gamersindo1223"
          gh_token: ${{ github.token }}
          useScraping: true
          limit: 100000
          readme_path: "gamersindo1223/gamersindo1223"
