on:
  schedule:
    # Runs every hour or use crontab.guru for custom cron
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest MAL history
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: MyAnimeList readme workflow
        uses: gamersindo1223/MAL-ReadmeList@main
        with:
          gh_token: ${{ github.token }}
          mal_username: "gamersindo1223"
          repo_branch: "main"
          repo_filename: "README.md"
          repo_path: "gamersindo1223/gamersindo1223"
